framework:
    secret: '%env(APP_SECRET)%'

    session:
        cookie_secure: auto   # "auto" => true si HTTPS
        cookie_httponly: true
        cookie_samesite: lax

    

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

